// --------------------------------------------------------------------------
//                   OpenMS -- Open-Source Mass Spectrometry
// --------------------------------------------------------------------------
// Copyright The OpenMS Team -- Eberhard Karls University Tuebingen,
// ETH Zurich, and Freie Universitaet Berlin 2002-2013.
// 
// This software is released under a three-clause BSD license:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of any author or any participating institution
//    may be used to endorse or promote products derived from this software
//    without specific prior written permission.
// For a full list of authors, refer to the file AUTHORS.
// --------------------------------------------------------------------------
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL ANY OF THE AUTHORS OR THE CONTRIBUTING
// INSTITUTIONS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
// 
// --------------------------------------------------------------------------
// $Maintainer: Jens Allmer $
// $Authors: Jens Allmer $
// --------------------------------------------------------------------------

#include <OpenMS/ANALYSIS/DENOVO/MSNOVOGEN/Chromosome.h>

namespace OpenMS
{

  Chromosome::Chromosome():
    sequence(""), score(0), charge(1)
  {
  }

  Chromosome::Chromosome(AASequence seq, double val) :
    sequence(seq), score(val), charge(1)
  {
  }

  Chromosome::Chromosome(AASequence seq, double val, int c) :
    sequence(seq), score(val), charge(c)
  {
  }

  Chromosome::Chromosome(const Chromosome& other)
  {
	  score = other.getScore();
	  setSequence(other.getSequence());
  }

  Chromosome & Chromosome::operator=(const Chromosome& rhs)
  {
	  if (this == &rhs)
		  return *this;

	  sequence = rhs.sequence;
	  score = rhs.score;

	  return *this;
  }

  double Chromosome::getScore() const
  {
    return score;
  }

  void Chromosome::setScore(double score) {
	this->score = score;
  }

  /// autogenerated getter for sequence member variable.
  const AASequence & Chromosome::getSequence() const
  {
	return sequence;
  }

  /// autogenerated setter for sequence member variable.
  void Chromosome::setSequence(AASequence sequence)
  {
	this->sequence = sequence;
  }

	bool Chromosome::sortScoreDesc(boost::shared_ptr<Chromosome> lhs, boost::shared_ptr<Chromosome> rhs)
	{
		return(lhs->getScore() > rhs->getScore());
	}

	bool Chromosome::sortScoreAsc(boost::shared_ptr<Chromosome> lhs, boost::shared_ptr<Chromosome> rhs)
	{
		return(lhs->getScore() < rhs->getScore());
	}

} // namespace
